spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Routine?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 8060
application:
  config:
    users-url: http://localhost:8090/api/v1/Users
    reunions-url: http://localhost:8010/api/v1/Reunions
    Interventions-url: http://localhost:8030/api/v1/Interventions
    Notifications-url: http://localhost:8050/api/v1/Notifications
    Routine-url: http://localhost:8060/api/v1/Routines

